export const inventoryData = [
  {
    id: "INV001",
    name: "Bath Towel",
    category: "Housekeeping",
    stock: 45,
    price: 99.99,
    status: "In Stock",
    supplier: "TechCorp",
  },
  {
    id: "INV002",
    name: "Hand Towel",
    category: "Housekeeping",
    stock: 12,
    price: 249.99,
    status: "Low Stock",
    supplier: "FurniMax",
  },
  {
    id: "INV003",
    name: "Bathrobe",
    category: "Garment",
    stock: 0,
    price: 79.99,
    status: "Out of Stock",
    supplier: "HomeGoods",
  },
  {
    id: "INV004",
    name: "Bedsheet",
    category: "Housekeeping",
    stock: 150,
    price: 12.99,
    status: "In Stock",
    supplier: "PaperPlus",
  },
  {
    id: "INV005",
    name: "Pillow case",
    category: "Housekeeping",
    stock: 8,
    price: 34.99,
    status: "Low Stock",
    supplier: "LightCo",
  },
];

export const customerData = [
  {
    id: "CUST001",
    name: "John Smith",
    email: "john.smith@email.com",
    phone: "+1 (555) 123-4567",
    totalOrders: 12,
    totalSpent: 1299.88,
    status: "Active",
    joinDate: "2023-01-15",
  },
  {
    id: "CUST002",
    name: "Sarah Johnson",
    email: "sarah.j@email.com",
    phone: "+1 (555) 987-6543",
    totalOrders: 8,
    totalSpent: 756.32,
    status: "Active",
    joinDate: "2023-03-22",
  },
  {
    id: "CUST003",
    name: "Mike Davis",
    email: "mike.davis@email.com",
    phone: "+1 (555) 456-7890",
    totalOrders: 3,
    totalSpent: 189.97,
    status: "Inactive",
    joinDate: "2023-08-10",
  },
  {
    id: "CUST004",
    name: "Emily Brown",
    email: "emily.brown@email.com",
    phone: "+1 (555) 321-0987",
    totalOrders: 15,
    totalSpent: 2145.67,
    status: "VIP",
    joinDate: "2022-11-05",
  },
  {
    id: "CUST005",
    name: "David Wilson",
    email: "d.wilson@email.com",
    phone: "+1 (555) 654-3210",
    totalOrders: 6,
    totalSpent: 432.15,
    status: "Active",
    joinDate: "2023-06-18",
  },
];
